version: '3.7'

networks:
  backend:
    driver: bridge

services:
  nginx:  
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile  # Use the Dockerfile you created
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - backend
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    ports:
      - "3386:3306"
    volumes:
      - "mysql-vol:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_php
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio-access-key
      - MINIO_SERVER_SECRET_KEY=minio-secret-key

  # redis
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./docker/redis:/var/log/redis
    ports:
      - "6379:6379"
    networks:
      - backend

  #minio
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - backend 
    volumes:
      - ./docker/minio:/data

volumes:
  mysql-vol:
