version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/laravel.Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./src:/var/www
    networks:
      - laravel_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    container_name: nginx-app
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel_network

  database:
    image: mysql:8.1.0
    container_name: database-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - laravel_network

  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_PORT2}:9001"
    # environment:
    #   MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    #   MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  redis:
    image: redis:7.2.0-alpine
    container_name: redis-app
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}
    volumes:
      - redisdb:/data
    

networks:
  laravel_network:
volumes:
  mysqldb:
  redisdb: